---
title: "What the Package Does (Title Case)"
output:
  github_document:
    fig_width: 9
    fig_height: 5
---

## Building

First build this package, then build its jars by running:

```{r eval=FALSE}
sparklyr::compile_package_jars()
```

then build the R package as usual.

## Getting Started

Connect and test this package as follows:

```{r}
library(variantspark)
library(sparklyr)
library(dplyr)
library(ggplot2)


sc <- spark_connect(master = "local", version = "2.2.0")
vsc <- vs_context(sc)
```

```{r}
hipster_vcf <- vs_read_vcf(vsc, "data/hipster.vcf.bz2")

# Names of loaded samples
sample_names(hipster_vcf, 3)

```

```{r}
hipster_label <- vs_read_csv(vsc, "data/hipster_labels.txt")

label <- invoke(vsc, "loadLabel", "data/hipster_labels.txt", "label") 
```

```{r}
importance <- vs_importance_analysis(vsc, hipster_vcf, label, 10)
importance_tbl <- importance_tbl(importance)
```


```{r}
# save a importance sample in memory
importance_df <- importance_tbl %>% 
  dplyr::arrange(-importance) %>% 
  head(20) %>% 
  collect()

# importance barplot
ggplot(importance_df) +
  aes(x = variable, y = importance) + 
  geom_bar(stat = 'identity') +          
  scale_x_discrete(limits = importance_df[order(importance_df$importance), 1]$variable) + 
  coord_flip()

```

```{r}
spark_disconnect_all()
```
